# GoReleaser v1 configuration (compatible with GitHub Actions)
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: remblob
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: techiecaro
      name: homebrew-tap
    homepage: "https://github.com/techiecaro/remblob"
    description: "Edit remote files locally."
    license: "MIT"
    folder: Formula
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "remblob"