# GoReleaser v2 configuration
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: remblob
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: techiecaro
      name: homebrew-tap
    homepage: "https://github.com/techiecaro/remblob"
    description: "Edit remote files locally."
    license: "MIT"
    directory: Formula
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "remblob"