version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: remblob
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: techiecaro
      name: homebrew-tap
    homepage: "https://github.com/techiecaro/remblob"
    description: "Edit remote files locally."
    license: "MIT"
    directory: Formula
